### PR TITLE
initial redbooth patch

### PR DESCRIPTION
**Pull request by sonnyp**
Resurrecting this repository as we're gonna patch Strophe.js a bit more.

This is our initial patch so this reflects what we have on production.

### CODE REVIEW

**Comment by mllocs** [comment]
:+1:

**Comment by csaura** [comment]
Our 2 thumbs policy was broken here!

**Comment by sonnyp** [comment]
@csaura: @mllocs and I agreed it wasn't needed as the code will be reviewed in frontend PR.

Do you think we should apply same policy here anyway?

**Comment by mllocs** [comment]
this code is already in production, @sonnyp was only syncing our fork

**Pull request merged**
